name: Run unit tests

on: [push, pull_request]

jobs:
    test-linux:
        runs-on: ubuntu-22.04
        env:
          CTEST_OUTPUT_ON_FAILURE: True
        steps:
          - name: Checkout
            uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
            with:
              ref: ${{ !github.event.pull_request.head.repo.fork && github.head_ref || '' }}

          - name: Setup Go environment
            uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9
            with:
              go-version: "1.20.4"
              cache: true

          - name: Unit Tests
            run: go test -v ./...
